import type { Student } from "./types"

export const students: Student[] = [
  { id: "1",  studentId: "24-1-00101", firstName: "Maria",    lastName: "Santos",     email: "maria.santos@university.edu.ph",     program: "BS Computer Science",       yearLevel: 3, status: "approved", registrationDate: "2024-06-15" },
  { id: "2",  studentId: "24-1-00102", firstName: "Juan",     lastName: "Dela Cruz",  email: "juan.delacruz@university.edu.ph",    program: "BS Information Technology",  yearLevel: 2, status: "approved", registrationDate: "2024-06-16" },
  { id: "3",  studentId: "24-1-00103", firstName: "Angela",   lastName: "Reyes",      email: "angela.reyes@university.edu.ph",     program: "BS Computer Science",       yearLevel: 4, status: "approved", registrationDate: "2024-06-15" },
  { id: "4",  studentId: "24-1-00104", firstName: "Carlos",   lastName: "Garcia",     email: "carlos.garcia@university.edu.ph",    program: "BS Information Systems",    yearLevel: 1, status: "pending",  registrationDate: "2024-08-20" },
  { id: "5",  studentId: "24-1-00105", firstName: "Patricia", lastName: "Navarro",    email: "patricia.navarro@university.edu.ph", program: "BS Computer Science",       yearLevel: 2, status: "approved", registrationDate: "2024-06-17" },
  { id: "6",  studentId: "24-1-00106", firstName: "Miguel",   lastName: "Torres",     email: "miguel.torres@university.edu.ph",    program: "BS Information Technology",  yearLevel: 3, status: "approved", registrationDate: "2024-06-18" },
  { id: "7",  studentId: "24-1-00107", firstName: "Sofia",    lastName: "Bautista",   email: "sofia.bautista@university.edu.ph",   program: "BS Information Systems",    yearLevel: 1, status: "pending",  registrationDate: "2024-08-22" },
  { id: "8",  studentId: "24-1-00108", firstName: "Rafael",   lastName: "Mendoza",    email: "rafael.mendoza@university.edu.ph",   program: "BS Computer Science",       yearLevel: 4, status: "approved", registrationDate: "2024-06-15" },
  { id: "9",  studentId: "24-1-00109", firstName: "Isabelle", lastName: "Cruz",       email: "isabelle.cruz@university.edu.ph",    program: "BS Information Technology",  yearLevel: 2, status: "approved", registrationDate: "2024-06-19" },
  { id: "10", studentId: "24-1-00110", firstName: "Daniel",   lastName: "Villanueva", email: "daniel.villanueva@university.edu.ph", program: "BS Computer Science",       yearLevel: 3, status: "rejected", registrationDate: "2024-07-01" },
  { id: "11", studentId: "24-1-00111", firstName: "Camille",  lastName: "Fernandez",  email: "camille.fernandez@university.edu.ph", program: "BS Information Systems",    yearLevel: 2, status: "approved", registrationDate: "2024-06-20" },
  { id: "12", studentId: "24-1-00112", firstName: "Andrei",   lastName: "Lopez",      email: "andrei.lopez@university.edu.ph",     program: "BS Computer Science",       yearLevel: 1, status: "pending",  registrationDate: "2024-08-25" },
  { id: "13", studentId: "24-1-00113", firstName: "Bianca",   lastName: "Rivera",     email: "bianca.rivera@university.edu.ph",    program: "BS Information Technology",  yearLevel: 4, status: "approved", registrationDate: "2024-06-16" },
  { id: "14", studentId: "24-1-00114", firstName: "Enrique",  lastName: "Castillo",   email: "enrique.castillo@university.edu.ph", program: "BS Computer Science",       yearLevel: 3, status: "approved", registrationDate: "2024-06-17" },
  { id: "15", studentId: "24-1-00115", firstName: "Daniella", lastName: "Aquino",     email: "daniella.aquino@university.edu.ph",  program: "BS Information Systems",    yearLevel: 2, status: "approved", registrationDate: "2024-06-21" },
  { id: "16", studentId: "24-1-00116", firstName: "Marco",    lastName: "Ramos",      email: "marco.ramos@university.edu.ph",      program: "BS Information Technology",  yearLevel: 1, status: "pending",  registrationDate: "2024-08-28" },
  { id: "17", studentId: "24-1-00117", firstName: "Jasmine",  lastName: "Gonzales",   email: "jasmine.gonzales@university.edu.ph", program: "BS Computer Science",       yearLevel: 4, status: "approved", registrationDate: "2024-06-15" },
  { id: "18", studentId: "24-1-00118", firstName: "Lorenzo",  lastName: "Perez",      email: "lorenzo.perez@university.edu.ph",    program: "BS Information Systems",    yearLevel: 3, status: "approved", registrationDate: "2024-06-22" },
  { id: "19", studentId: "24-1-00119", firstName: "Nicole",   lastName: "Tan",        email: "nicole.tan@university.edu.ph",       program: "BS Information Technology",  yearLevel: 2, status: "approved", registrationDate: "2024-06-23" },
  { id: "20", studentId: "24-1-00120", firstName: "Gabriel",  lastName: "Lim",        email: "gabriel.lim@university.edu.ph",      program: "BS Computer Science",       yearLevel: 1, status: "pending",  registrationDate: "2024-09-01" },
]
