export type StudentStatus = "pending" | "approved" | "rejected"
export type FeeStatus = "paid" | "unpaid" | "partial"
export type FineStatus = "unpaid" | "paid" | "waived"
export type AttendanceStatus = "present" | "absent" | "excused"
export type ClearanceItemStatus = "cleared" | "pending" | "not-cleared"
export type EventType = "general-assembly" | "seminar" | "workshop" | "social" | "meeting"
export type PaymentStatus = "pending" | "approved" | "declined"
export type PaymentType = "membership-fee" | "fine"

export interface Student {
  id: string
  studentId: string
  firstName: string
  lastName: string
  email: string
  course: string
  yearLevel: number
  section: string
  status: StudentStatus
  registrationDate: string
  avatarUrl?: string
}

export interface MembershipFee {
  id: string
  studentId: string
  studentName: string
  amount: number
  semester: string
  academicYear: string
  status: FeeStatus
  paidDate?: string
  receiptNo?: string
}

export interface Event {
  id: string
  name: string
  description: string
  date: string
  location: string
  type: EventType
  attendeesCount: number
  totalStudents: number
}

export interface EventAttendance {
  id: string
  eventId: string
  eventName: string
  studentId: string
  studentName: string
  status: AttendanceStatus
  timeIn?: string
}

export interface Fine {
  id: string
  studentId: string
  studentName: string
  reason: string
  amount: number
  status: FineStatus
  dateIssued: string
  datePaid?: string
  eventId?: string // Link to event if fine is from missed attendance
  autoGenerated?: boolean // Flag to indicate if fine was auto-generated
}

export interface ClearanceRequirement {
  name: string
  status: ClearanceItemStatus
}

export interface Clearance {
  id: string
  studentId: string
  studentName: string
  academicYear: string
  semester: string
  requirements: ClearanceRequirement[]
  overallStatus: ClearanceItemStatus
}

export interface FinancialSummary {
  totalCollected: number
  totalFines: number
  totalPending: number
  totalStudents: number
  monthlyCollections: { month: string; amount: number }[]
  feeStatusBreakdown: { status: string; count: number }[]
  fineStatusBreakdown: { status: string; count: number }[]
}

export interface Payment {
  id: string
  studentId: string
  studentName: string
  type: PaymentType
  amount: number
  referenceCode: string
  receiptImage: string // URL or base64 of the uploaded receipt
  status: PaymentStatus
  submittedDate: string
  reviewedDate?: string
  reviewedBy?: string
  remarks?: string // For declined payments
  relatedId?: string // ID of membership fee or fine this payment is for
}
