import type { Fine } from "./types"

// Fines can be auto-generated when students are marked absent from mandatory events.
// Auto-generated fines have `autoGenerated: true` and `eventId` set to the event.
export const fines: Fine[] = [
  { id: "fn1", studentId: "2024-00103", studentName: "Angela Reyes", reason: "Absent - General Assembly 2024", amount: 50, status: "unpaid", dateIssued: "2024-09-16", eventId: "e1", autoGenerated: true },
  { id: "fn2", studentId: "2024-00106", studentName: "Miguel Torres", reason: "Late submission of requirements", amount: 25, status: "paid", dateIssued: "2024-09-20", datePaid: "2024-09-25", autoGenerated: false },
  { id: "fn3", studentId: "2024-00109", studentName: "Isabelle Cruz", reason: "Absent - Leadership Seminar", amount: 50, status: "unpaid", dateIssued: "2024-10-06", eventId: "e2", autoGenerated: true },
  { id: "fn4", studentId: "2024-00110", studentName: "Daniel Villanueva", reason: "Absent - General Assembly 2024", amount: 50, status: "unpaid", dateIssued: "2024-09-16", eventId: "e1", autoGenerated: true },
  { id: "fn5", studentId: "2024-00110", studentName: "Daniel Villanueva", reason: "Absent - USSC Welcome Party", amount: 50, status: "unpaid", dateIssued: "2024-09-01", eventId: "e4", autoGenerated: true },
  { id: "fn6", studentId: "2024-00102", studentName: "Juan Dela Cruz", reason: "Late payment of membership fee", amount: 25, status: "paid", dateIssued: "2024-08-01", datePaid: "2024-08-05", autoGenerated: false },
  { id: "fn7", studentId: "2024-00114", studentName: "Enrique Castillo", reason: "Violation of event guidelines", amount: 100, status: "waived", dateIssued: "2024-10-21", autoGenerated: false },
  { id: "fn8", studentId: "2024-00105", studentName: "Patricia Navarro", reason: "Absent - Budget Planning Meeting", amount: 50, status: "unpaid", dateIssued: "2024-11-11", eventId: "e5", autoGenerated: true },
  { id: "fn9", studentId: "2024-00118", studentName: "Lorenzo Perez", reason: "Absent - Community Outreach", amount: 75, status: "unpaid", dateIssued: "2024-11-26", eventId: "e6", autoGenerated: true },
  { id: "fn10", studentId: "2024-00111", studentName: "Camille Fernandez", reason: "Late submission of clearance docs", amount: 25, status: "paid", dateIssued: "2024-10-15", datePaid: "2024-10-20", autoGenerated: false },
]
