import type { Event, EventAttendance } from "./types"

export const events: Event[] = [
  {
    id: "e1",
    name: "General Assembly 2024",
    date: "2024-09-15",
    majorEvent: true,
    timeInStart: "08:00",
    timeInEnd: "09:00",
    timeOutStart: "17:00",
    timeOutEnd: "18:00",
    location: "University Auditorium",
    note: "Attendance is mandatory for all USSC members.",
    attendees: 156,
    status: "completed",
  },
  {
    id: "e2",
    name: "Leadership Seminar",
    date: "2024-10-05",
    timeInStart: "09:00",
    timeInEnd: "09:30",
    location: "Conference Hall A",
    note: "Seminar on student leadership and governance.",
    attendees: 89,
    status: "completed",
  },
  {
    id: "e3",
    name: "Tech Workshop: Web Dev",
    date: "2024-10-20",
    timeInStart: "13:00",
    timeInEnd: "13:30",
    location: "Computer Lab 3",
    note: "Hands-on workshop on modern web development technologies.",
    attendees: 45,
    status: "completed",
  },
  {
    id: "e4",
    name: "USSC Welcome Party",
    date: "2024-08-30",
    location: "University Grounds",
    note: "Welcome party for new members and freshmen.",
    attendees: 178,
    status: "completed",
  },
  {
    id: "e5",
    name: "Budget Planning Meeting",
    date: "2025-02-10",
    timeInStart: "10:00",
    timeInEnd: "10:15",
    location: "Meeting Room 2",
    note: "Quarterly budget review and planning session.",
    attendees: 0,
    status: "upcoming",
  },
  {
    id: "e6",
    name: "Community Outreach Program",
    date: "2025-03-05",
    location: "Barangay Hall",
    note: "Community service and outreach program.",
    attendees: 0,
    status: "upcoming",
  },
  {
    id: "e7",
    name: "Year-end Celebration",
    date: "2025-04-28",
    majorEvent: true,
    location: "University Gym",
    note: "",
    attendees: 0,
    status: "upcoming",
  },
  {
    id: "e8",
    name: "Campus Cleanup Drive",
    date: "2025-02-27",
    timeInStart: "07:00",
    timeInEnd: "07:30",
    timeOutStart: "10:00",
    timeOutEnd: "10:30",
    location: "University Campus",
    note: "Ongoing campus cleanup initiative.",
    attendees: 34,
    status: "ongoing",
  },
]

export const eventAttendance: EventAttendance[] = [
  { id: "ea1", eventId: "e1", eventName: "General Assembly 2024", studentId: "2024-00101", studentName: "Maria Santos", status: "present", timeIn: "08:05" },
  { id: "ea2", eventId: "e1", eventName: "General Assembly 2024", studentId: "2024-00102", studentName: "Juan Dela Cruz", status: "present", timeIn: "08:20" },
  { id: "ea3", eventId: "e1", eventName: "General Assembly 2024", studentId: "2024-00103", studentName: "Angela Reyes", status: "absent" },
  { id: "ea4", eventId: "e1", eventName: "General Assembly 2024", studentId: "2024-00105", studentName: "Patricia Navarro", status: "present", timeIn: "08:00" },
  { id: "ea5", eventId: "e1", eventName: "General Assembly 2024", studentId: "2024-00106", studentName: "Miguel Torres", status: "excused" },
  { id: "ea6", eventId: "e2", eventName: "Leadership Seminar", studentId: "2024-00101", studentName: "Maria Santos", status: "present", timeIn: "09:05" },
  { id: "ea7", eventId: "e2", eventName: "Leadership Seminar", studentId: "2024-00108", studentName: "Rafael Mendoza", status: "present", timeIn: "09:10" },
  { id: "ea8", eventId: "e2", eventName: "Leadership Seminar", studentId: "2024-00109", studentName: "Isabelle Cruz", status: "absent" },
  { id: "ea9", eventId: "e3", eventName: "Tech Workshop: Web Dev", studentId: "2024-00101", studentName: "Maria Santos", status: "present", timeIn: "13:00" },
  { id: "ea10", eventId: "e3", eventName: "Tech Workshop: Web Dev", studentId: "2024-00102", studentName: "Juan Dela Cruz", status: "present", timeIn: "13:05" },
  { id: "ea11", eventId: "e8", eventName: "Campus Cleanup Drive", studentId: "2024-00101", studentName: "Maria Santos", status: "present", timeIn: "07:05" },
  { id: "ea12", eventId: "e8", eventName: "Campus Cleanup Drive", studentId: "2024-00106", studentName: "Miguel Torres", status: "present", timeIn: "07:12" },
]
